import { preload } from 'react-dom';
import images from '@/data/images.json';

function variants(name) {
  const meta = images[name];
  if (!meta) throw new Error(`<Picture>: unknown image "${name}". Run \`npm run images\`.`);
  const base = `/media/${name}.${meta.hash}`;
  const fallbackWidth = meta.widths.find((w) => w >= 640) ?? meta.widths.at(-1);
  return {
    meta,
    srcSet: (ext) => meta.widths.map((w) => `${base}-${w}.${ext} ${w}w`).join(', '),
    fallback: (ext) => `${base}-${fallbackWidth}.${ext}`,
  };
}

/**
 * Responsive <picture> for images generated by `npm run images`.
 * Serves AVIF with a WebP fallback, picks the right width from `sizes`, and
 * lazy-loads unless `priority` is set (use that only for the first visible
 * hero image).
 *
 * `art` swaps in a differently cropped image for some screens, e.g.
 * { name: 'storefront-portrait', media: '(max-aspect-ratio: 3/4)', sizes: '100vw' }.
 *
 * <picture> is rendered with `display: contents`, so styles written for the
 * <img> (object-fit, sizing, hover effects) keep working unchanged.
 */
export default function Picture({
  name,
  alt,
  sizes = '100vw',
  art,
  priority = false,
  lazy = !priority,
  className,
  style,
  blur = true,
  ...rest
}) {
  const main = variants(name);
  const alt2 = art ? variants(art.name) : null;
  const artSizes = art?.sizes ?? sizes;

  if (priority) {
    if (alt2) {
      preload(alt2.fallback('avif'), {
        as: 'image',
        type: 'image/avif',
        imageSrcSet: alt2.srcSet('avif'),
        imageSizes: artSizes,
        fetchPriority: 'high',
        media: art.media,
      });
    }
    preload(main.fallback('avif'), {
      as: 'image',
      type: 'image/avif',
      imageSrcSet: main.srcSet('avif'),
      imageSizes: sizes,
      fetchPriority: 'high',
      media: alt2 ? `not all and ${art.media}` : undefined,
    });
  }

  const placeholder =
    blur && main.meta.blur
      ? { backgroundImage: `url("${main.meta.blur}")`, backgroundSize: 'cover', backgroundPosition: 'center' }
      : null;

  return (
    <picture style={{ display: 'contents' }}>
      {alt2 && (
        <>
          <source media={art.media} type="image/avif" srcSet={alt2.srcSet('avif')} sizes={artSizes} />
          <source media={art.media} type="image/webp" srcSet={alt2.srcSet('webp')} sizes={artSizes} />
        </>
      )}
      <source type="image/avif" srcSet={main.srcSet('avif')} sizes={sizes} />
      <img
        src={main.fallback('webp')}
        srcSet={main.srcSet('webp')}
        sizes={sizes}
        width={main.meta.w}
        height={main.meta.h}
        alt={alt}
        loading={lazy ? 'lazy' : 'eager'}
        fetchPriority={priority ? 'high' : undefined}
        decoding="async"
        className={className}
        style={placeholder ? { ...placeholder, ...style } : style}
        {...rest}
      />
    </picture>
  );
}
